ARTIST_INSTRUMENTS = [
	'Voice',
	'Soprano (voice)',
	'Alto (voice)',
	'Mezzo Soprano (voice)',
	'Counter Tenor (voice)',
	'Tenor (voice)',
	'Baritone (voice)',
	'Bass (voice)',
	'Bassoon',
	'Contra Bassoon',
	'Clarinet',
	'Flute',
	'Piccolo',
	'Oboe',
	'Saxophone',
	'French horn',
	'Trombone',
	'Trumpet',
	'Tuba',
	'Percussion (orchestral)',
	'Drum set',
	'Bongos',
	'Timpani',
	'Marimba',
	'Xylophone',
	'Viola',
	'Violin',
	'Cello',
	'Double bass',
	'Fiddle',
	'Guitar',
	'Acoustic guitar',
	'Electric guitar',
	'Ukulele',
	'Slack key guitar',
	'Ipu',
	'Bass guitar',
	'Banjo',
	'Mandolin',
	'Accordion',
	'Bagpipes',
	'Recorder',
	'Pan pipes',
	'Sitar',
	'Zither',
	'Koto',
	'Pipa',
	'Bamboo flute',
	'Erhu',
	'Guzheng',
	'Guqin',
	'Lute',
	'Lyre',
	'Harp',
	'Piano',
	'Harpsichord',
	'Organ',
	'Voice Instructor',
	'Bassoon Instructor',
	'Contra Bassoon  Instructor',
	'Clarinet Instructor',
	'Flute Instructor',
	'Piccolo  Instructor',
	'Oboe Instructor',
	'Saxophone Instructor',
	'French horn Instructor',
	'Trombone Instructor',
	'Trumpet Instructor',
	'Tuba Instructor',
	'Percussion Instructor',
	'Drum set  Instructor',
	'Bongos Instructor',
	'Timpani Instructor',
	'Marimba Instructor',
	'Xylophone Instructor',
	'Viola Instructor',
	'Violin Instructor',
	'Cello Instructor',
	'Double bass Instructor',
	'Fiddle Instructor',
	'Guitar Instructor',
	'Acoustic guitar Instructor',
	'Electric guitar Instructor',
	'Ukulele Instructor',
	'Slack key guitar Instructor',
	'Ipu Instructor',
	'Bass guitar Instructor',
	'Banjo Instructor',
	'Mandolin Instructor',
	'Accordion Instructor',
	'Bagpipes Instructor',
	'Recorder Instructor',
	'Pan pipes Instructor',
	'Sitar Instructor',
	'Zither Instructor',
	'Koto Instructor',
	'Pipa Instructor',
	'Bamboo flute Instructor',
	'Erhu Instructor',
	'Guzheng Instructor',
	'Guqin Instructor',
	'Lute Instructor',
	'Lyre Instructor',
	'Harp Instructor',
	'Piano Instructor',
	'Harpsichord Instructor',
	'Organ Instructor',
]

TIMEFRAME_OF_POST_OPTIONS = [
	'3_days', '5_days', '1_weeks', '2_weeks', '1_months', '2_months', 'until_filled'
]